/*
 * BlueCaterpillarUI.java
 *
 * Created on 17 de agosto de 2006, 12:31
 */

package gui;

import bluecaterpillar.PopulationManager;

import java.util.*;
import javax.swing.*;
import java.awt.Cursor;
import java.text.DecimalFormat;

/**
 *
 * @author  julian
 */
public class BlueCaterpillarUI extends javax.swing.JFrame {
    
    //private Timer timer;    
    private PopulationManager pm = null;
    private Results results = null;
    
    /** Creates new form BlueCaterpillarUI */
    public BlueCaterpillarUI() {
        initComponents();
        
        SamplesToAssignList.setModel(new DefaultListModel());
        ReferencePopulationList.setModel(new DefaultListModel());
        
        BootstrapSpinner.setModel(new SpinnerNumberModel(100, 100, 100000, 100));
        RaritySpinner.setModel(new SpinnerNumberModel(0.01, 0.01, 0.5, 0.01));
      
        constantSpinner.setModel(new SpinnerNumberModel(0.0000, 0.0000, 1.0000, 0.0001));
        JSpinner.NumberEditor editor = (JSpinner.NumberEditor) constantSpinner.getEditor();
        DecimalFormat format = editor.getFormat();
        format.setMinimumFractionDigits(4);
        format.setMaximumFractionDigits(4);    
        
        rateSpinner.setModel(new SpinnerNumberModel(0.0000, 0.0000, 1.0000, 0.0001));
        
        editor = (JSpinner.NumberEditor) rateSpinner.getEditor();
        format = editor.getFormat();
        format.setMinimumFractionDigits(4);
        format.setMaximumFractionDigits(4);         

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SamplesToAssignList = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReferencePopulationList = new javax.swing.JList();
        moveToReferenceButton = new javax.swing.JButton();
        moveToSamplesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        OptionsPanel = new javax.swing.JPanel();
        NeisStandardDistance = new javax.swing.JCheckBox();
        NeisMinimumDistance = new javax.swing.JCheckBox();
        NeisDaDistance = new javax.swing.JCheckBox();
        ChordDistance = new javax.swing.JCheckBox();
        GoldsteinDistance = new javax.swing.JCheckBox();
        Likelihood = new javax.swing.JCheckBox();
        SLambda = new javax.swing.JCheckBox();
        ConformityMethod = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BootstrapSpinner = new javax.swing.JSpinner();
        RaritySpinner = new javax.swing.JSpinner();
        constantRadioButton = new javax.swing.JRadioButton();
        inverseRadioButton = new javax.swing.JRadioButton();
        constantSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        rateSpinner = new javax.swing.JSpinner();
        OpenFileButton = new javax.swing.JButton();
        RunButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blue Caterpillar");
        setResizable(false);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hoo R U?"));
        jScrollPane2.setViewportView(SamplesToAssignList);

        jScrollPane1.setViewportView(ReferencePopulationList);

        moveToReferenceButton.setText("<<");
        moveToReferenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveToReferenceButtonActionPerformed(evt);
            }
        });

        moveToSamplesButton.setText(">>");
        moveToSamplesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveToSamplesButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Reference populations");

        jLabel2.setText("Samples to assign");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(moveToSamplesButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(moveToReferenceButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(moveToSamplesButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(moveToReferenceButton))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .add(jScrollPane2, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        OptionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        NeisStandardDistance.setText(" Nei's standard distance");
        NeisStandardDistance.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        NeisStandardDistance.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NeisStandardDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeisStandardDistanceActionPerformed(evt);
            }
        });

        NeisMinimumDistance.setText(" Nei's minimum distance");
        NeisMinimumDistance.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        NeisMinimumDistance.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NeisMinimumDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeisMinimumDistanceActionPerformed(evt);
            }
        });

        NeisDaDistance.setText(" Nei's Da distance");
        NeisDaDistance.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        NeisDaDistance.setMargin(new java.awt.Insets(0, 0, 0, 0));
        NeisDaDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeisDaDistanceActionPerformed(evt);
            }
        });

        ChordDistance.setText(" Chord distance");
        ChordDistance.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ChordDistance.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ChordDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChordDistanceActionPerformed(evt);
            }
        });

        GoldsteinDistance.setText(" Goldstein's distance");
        GoldsteinDistance.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        GoldsteinDistance.setMargin(new java.awt.Insets(0, 0, 0, 0));

        Likelihood.setText(" Likelihood");
        Likelihood.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        Likelihood.setMargin(new java.awt.Insets(0, 0, 0, 0));
        Likelihood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LikelihoodActionPerformed(evt);
            }
        });

        SLambda.setText(" S - lambda");
        SLambda.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        SLambda.setMargin(new java.awt.Insets(0, 0, 0, 0));

        ConformityMethod.setText(" Conformity method");
        ConformityMethod.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ConformityMethod.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ConformityMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConformityMethodActionPerformed(evt);
            }
        });

        jLabel3.setText("Rarity");

        jLabel4.setText("Bootstrap  (100 - 100,000)");

        RaritySpinner.setEnabled(false);

        constantRadioButton.setSelected(true);
        constantRadioButton.setText("Constant");
        constantRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        constantRadioButton.setEnabled(false);
        constantRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        constantRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constantRadioButtonActionPerformed(evt);
            }
        });

        inverseRadioButton.setText("Inverse sample size");
        inverseRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        inverseRadioButton.setEnabled(false);
        inverseRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        inverseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inverseRadioButtonActionPerformed(evt);
            }
        });

        constantSpinner.setEnabled(false);

        jLabel5.setText("Mutation rate");

        org.jdesktop.layout.GroupLayout OptionsPanelLayout = new org.jdesktop.layout.GroupLayout(OptionsPanel);
        OptionsPanel.setLayout(OptionsPanelLayout);
        OptionsPanelLayout.setHorizontalGroup(
            OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(OptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(GoldsteinDistance)
                    .add(SLambda)
                    .add(ChordDistance)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, OptionsPanelLayout.createSequentialGroup()
                        .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(OptionsPanelLayout.createSequentialGroup()
                                .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(NeisMinimumDistance)
                                    .add(NeisStandardDistance)
                                    .add(OptionsPanelLayout.createSequentialGroup()
                                        .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, OptionsPanelLayout.createSequentialGroup()
                                                .add(Likelihood)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(inverseRadioButton)
                                                    .add(OptionsPanelLayout.createSequentialGroup()
                                                        .add(constantRadioButton)
                                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                        .add(constantSpinner, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))))
                                            .add(org.jdesktop.layout.GroupLayout.LEADING, OptionsPanelLayout.createSequentialGroup()
                                                .add(ConformityMethod)
                                                .add(13, 13, 13)
                                                .add(jLabel3)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(RaritySpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                        .add(102, 102, 102)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                            .add(OptionsPanelLayout.createSequentialGroup()
                                .add(NeisDaDistance)
                                .add(190, 190, 190)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)
                        .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(OptionsPanelLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, BootstrapSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4)))
                            .add(OptionsPanelLayout.createSequentialGroup()
                                .add(19, 19, 19)
                                .add(rateSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .add(65, 65, 65))
        );
        OptionsPanelLayout.setVerticalGroup(
            OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(OptionsPanelLayout.createSequentialGroup()
                .add(NeisStandardDistance)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(NeisMinimumDistance)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(OptionsPanelLayout.createSequentialGroup()
                        .add(NeisDaDistance)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ChordDistance)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SLambda)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(GoldsteinDistance)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ConformityMethod)
                            .add(jLabel3)
                            .add(RaritySpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5)
                            .add(rateSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(16, 16, 16)
                        .add(OptionsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(Likelihood)
                            .add(constantRadioButton)
                            .add(constantSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(inverseRadioButton))
                    .add(BootstrapSpinner, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OptionsPanelLayout.linkSize(new java.awt.Component[] {ChordDistance, GoldsteinDistance, RaritySpinner, jLabel3}, org.jdesktop.layout.GroupLayout.VERTICAL);

        OpenFileButton.setText("Open Input File");
        OpenFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileButtonActionPerformed(evt);
            }
        });

        RunButton.setText("Run");
        RunButton.setEnabled(false);
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, OptionsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(aboutButton)
                                .add(OpenFileButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(RunButton))
                        .add(88, 88, 88)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {OpenFileButton, RunButton, aboutButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(OpenFileButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(RunButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(aboutButton))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(36, 36, 36)
                .add(OptionsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        String msg = new String("Blue Caterpillar v2.0 beta" + "\n" +
                                "By Miguel de Navascués and Julián de Navascués" + "\n" +
                                "http://m.navascues.googlepages.com" + "\n" +
                                "m.navascues@gmail.com");
        JOptionPane.showMessageDialog(this, msg, "About...", JOptionPane.WARNING_MESSAGE);                    
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void inverseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inverseRadioButtonActionPerformed
        if (inverseRadioButton.isSelected()){
            constantRadioButton.setSelected(false);        
        }else{
            constantRadioButton.setSelected(true);        
        }
    }//GEN-LAST:event_inverseRadioButtonActionPerformed

    private void constantRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constantRadioButtonActionPerformed
        if (constantRadioButton.isSelected()){
            inverseRadioButton.setSelected(false);        
        }else{
            inverseRadioButton.setSelected(true);        
        }
    }//GEN-LAST:event_constantRadioButtonActionPerformed

    private void ConformityMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConformityMethodActionPerformed
        if (ConformityMethod.isSelected()){
            RaritySpinner.setEnabled(true);
        }else{
            RaritySpinner.setEnabled(false);
        }
    }//GEN-LAST:event_ConformityMethodActionPerformed

    private void LikelihoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LikelihoodActionPerformed

        if (Likelihood.isSelected()){
            constantRadioButton.setEnabled(true);
            constantSpinner.setEnabled(true);
            inverseRadioButton.setEnabled(true);        
        }else{
            constantRadioButton.setEnabled(false);
            constantSpinner.setEnabled(false);
            inverseRadioButton.setEnabled(false);                
        }
    }//GEN-LAST:event_LikelihoodActionPerformed

    private void ChordDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChordDistanceActionPerformed
        if (!ChordDistance.isSelected()){ 
            NeisDaDistance.setSelected(false);
            NeisMinimumDistance.setSelected(false);
            NeisStandardDistance.setSelected(false);
        }else{
            NeisDaDistance.setSelected(true);
            NeisMinimumDistance.setSelected(true);
            NeisStandardDistance.setSelected(true);        
        }
    }//GEN-LAST:event_ChordDistanceActionPerformed

    private void NeisDaDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeisDaDistanceActionPerformed
        if (!NeisDaDistance.isSelected()){ 
            ChordDistance.setSelected(false);
            NeisMinimumDistance.setSelected(false);
            NeisStandardDistance.setSelected(false);
        }else{
            ChordDistance.setSelected(true);
            NeisMinimumDistance.setSelected(true);
            NeisStandardDistance.setSelected(true);        
        }
    }//GEN-LAST:event_NeisDaDistanceActionPerformed

    private void NeisMinimumDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeisMinimumDistanceActionPerformed
        if (!NeisMinimumDistance.isSelected()){ 
            ChordDistance.setSelected(false);
            NeisDaDistance.setSelected(false);
            NeisStandardDistance.setSelected(false);
        }else{
            ChordDistance.setSelected(true);
            NeisDaDistance.setSelected(true);
            NeisStandardDistance.setSelected(true);        
        }
    }//GEN-LAST:event_NeisMinimumDistanceActionPerformed

    private void NeisStandardDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeisStandardDistanceActionPerformed
        if (!NeisStandardDistance.isSelected()){ 
            ChordDistance.setSelected(false);
            NeisDaDistance.setSelected(false);
            NeisMinimumDistance.setSelected(false);
        }else{
            ChordDistance.setSelected(true);
            NeisDaDistance.setSelected(true);
            NeisMinimumDistance.setSelected(true);        
        }
        
    }//GEN-LAST:event_NeisStandardDistanceActionPerformed

    private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed

        if  ( ! (NeisStandardDistance.isSelected() || ChordDistance.isSelected() || 
                NeisDaDistance.isSelected() || NeisMinimumDistance.isSelected() ||
                GoldsteinDistance.isSelected() || SLambda.isSelected() ||
                Likelihood.isSelected() || ConformityMethod.isSelected()))
        {
            JOptionPane.showMessageDialog(this, "Choose a method.", "Oops!", JOptionPane.ERROR_MESSAGE);            
            return;        
        }
                
        DefaultListModel model_samples = (DefaultListModel) SamplesToAssignList.getModel();
        DefaultListModel model_referemces = (DefaultListModel) ReferencePopulationList.getModel();
        
        if (model_samples.getSize() == 0 || model_referemces.getSize() == 0)
        {
            JOptionPane.showMessageDialog(this, "I need at least one sample and one reference.", "Oops!", JOptionPane.ERROR_MESSAGE);            
            return;
        }        
        
        String [] populations_Y = new String [ model_samples.getSize()];
        String [] populations_X = new String [ model_referemces.getSize()];
        
        for (int i = 0; i < model_samples.getSize(); i++)
            populations_Y[i] = (String) model_samples.elementAt(i);
        
        for (int i = 0; i < model_referemces.getSize(); i++)
            populations_X[i] = (String) model_referemces.elementAt(i);
       
        results = new Results(this, pm);
        results.setMaximum(model_samples.getSize() * model_referemces.getSize() * (Integer) BootstrapSpinner.getValue());
                
        pm.configure(
                (Integer) BootstrapSpinner.getValue(), 
                populations_X, populations_Y, 
                (Double) RaritySpinner.getValue(),
                NeisStandardDistance.isSelected() || ChordDistance.isSelected() || NeisDaDistance.isSelected() || NeisMinimumDistance.isSelected(),
                GoldsteinDistance.isSelected(),
                SLambda.isSelected(),
                Likelihood.isSelected(),
                ConformityMethod.isSelected(),
                constantRadioButton.isSelected(),
                (Double) constantSpinner.getValue(),
                (Double) rateSpinner.getValue(), // rate
                results);        
        
        results.setModal(true);
        results.setVisible(true);        
        
    }//GEN-LAST:event_RunButtonActionPerformed
    
    private void moveToReferenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveToReferenceButtonActionPerformed
        if (! SamplesToAssignList.isSelectionEmpty()){
            DefaultListModel m = (DefaultListModel) SamplesToAssignList.getModel();
            int selected = SamplesToAssignList.getSelectedIndex();
            String name = (String) m.getElementAt(selected);
            m.removeElementAt(selected);
            
            DefaultListModel m2 = (DefaultListModel) ReferencePopulationList.getModel();
            m2.addElement(name);
            pm.setAsReference(name);
        }
    }//GEN-LAST:event_moveToReferenceButtonActionPerformed

    private void moveToSamplesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveToSamplesButtonActionPerformed
        if (! ReferencePopulationList.isSelectionEmpty()){
            DefaultListModel m = (DefaultListModel) ReferencePopulationList.getModel();
            int selected = ReferencePopulationList.getSelectedIndex();
            String name = (String) m.getElementAt(selected);
            m.removeElementAt(selected);
            DefaultListModel m2 = (DefaultListModel) SamplesToAssignList.getModel();
            m2.addElement(name);
            pm.unsetAsReference(name);
        }
    }//GEN-LAST:event_moveToSamplesButtonActionPerformed

    private void OpenFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileButtonActionPerformed
    // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            try {
            
                pm = new PopulationManager(chooser.getSelectedFile().getAbsolutePath());
                this.setPopulationReferences();
                RunButton.setEnabled(true);
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage(), "Oops!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_OpenFileButtonActionPerformed
    
    void setPopulationReferences(){
        String[] names = pm.getPopulationNames();
        
        DefaultListModel m = (DefaultListModel) ReferencePopulationList.getModel();
        m.clear();
        
        for (int i = 0; i < names.length; i++)
            m.add(i, names[i]);
       
        DefaultListModel model = (DefaultListModel) SamplesToAssignList.getModel();
        model.clear();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner BootstrapSpinner;
    private javax.swing.JCheckBox ChordDistance;
    private javax.swing.JCheckBox ConformityMethod;
    private javax.swing.JCheckBox GoldsteinDistance;
    private javax.swing.JCheckBox Likelihood;
    private javax.swing.JCheckBox NeisDaDistance;
    private javax.swing.JCheckBox NeisMinimumDistance;
    private javax.swing.JCheckBox NeisStandardDistance;
    private javax.swing.JButton OpenFileButton;
    private javax.swing.JPanel OptionsPanel;
    private javax.swing.JSpinner RaritySpinner;
    private javax.swing.JList ReferencePopulationList;
    private javax.swing.JButton RunButton;
    private javax.swing.JCheckBox SLambda;
    private javax.swing.JList SamplesToAssignList;
    private javax.swing.JButton aboutButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton constantRadioButton;
    private javax.swing.JSpinner constantSpinner;
    private javax.swing.JRadioButton inverseRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton moveToReferenceButton;
    private javax.swing.JButton moveToSamplesButton;
    private javax.swing.JSpinner rateSpinner;
    // End of variables declaration//GEN-END:variables
    
}
